<div id="order-shipping-method-choose" style="display: none">
        <div class="shipment-methods">
            <div id="s_method_freeshipping" class="shipping-method-item checkout-item">
                <span>Free Shipping : Free</span>
            </div>
            <input type="hidden" value="freeshipping_freeshipping" name="order[shipping_method]"
                   id="order_shipping_method_hidden">
        </div>
    </div>

</div>