<?php
    $this->updateTax();
    $_items = $this->getItems();
    $quote_id = $this->getRequest()->getParam('id');
    if(isset($quote_id)){
        $_items = Mage::registry('quote_items');
    }
?>

<div id="order-items_grid" class="grid order-edit">
	<table cellspacing="0" class="data order-tables">
		<colgroup>
			<col width="10">
			<col width="20">
			<col width="">
			<col width="150">
			<col width="150">
			<col width="120">
			<col width="120">
		</colgroup>
		<thead>
		<tr class="headings">
			<th class="a-center">Action</th>
			<th class="a-center">Item ID</th>
			<th class="a-left">Name</th>
			<th class="a-center">Qty</th>
			<th class="a-right">Price</th>
			<th class="a-center">Tax</th>
			<th class="a-right">Total</th>
		</tr>
		</thead>
		<tbody>
        <?php $i = 0; ?>
        <?php foreach ($_items as $_item){$i++ ?>
            <tr id="order_item_<?php echo $_item->getId() ?>" item_id="<?php echo $_item->getId() ?>" product_id="<?php echo $_item->getProduct()->getId() ?>" class="hover">
                <td class="a-center"><a class="remove" onclick="remove_item('<?php echo $_item->getId() ?>')"><span><strong>Remove</strong></span></a></td>
                <td class="a-center"><?php echo $_item->getId(); ?></td>
                <td class="a-left"><h5><span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->htmlEscape($_item->getName()) ?></span></h5>
                    <div><strong>SKU:</strong><?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($_item->getSku()))); ?></div>
                    <?php if ($_item->getMessage(false)): ?>
                        <?php if ($_item->getHasError()): ?>
                            <div class="error">
                                <div style="font-size:95%"><?php echo $_item->getMessage() ?></div>
                            </div>
                        <?php else: ?>
                            <?php foreach ($_item->getMessage(false) as $message): ?>
                                <div class=">notice">
                                    <div style="font-size:95%"><?php echo $message; ?></div>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td class="qty a-center"><input id="item_qty_<?php echo $_item->getId() ?>" value="<?php echo $_item->getQty() * 1 ?>" name="item[<?php echo $_item->getId() ?>][qty]" class="input-text input-qty" onblur="order.itemsUpdate()"></td>
                <td class="price a-center">
                    <input value='<?php echo sprintf("%.2f", $this->getOriginalEditablePrice($_item)) ?>' name="item[<?php echo $_item->getId() ?>][custom_price]" id="item_custom_price_<?php echo $_item->getId() ?>" class="input-text input-price" onblur="order.itemsUpdate()">
                </td>
                <td class="a-center"><?php echo sprintf("%.2f",$_item->getTaxPercent()); ?>%</td>
                <td id="price-<?php echo $_item->getId() ?>" class="a-right">
                    <?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
                        <br /><span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                    <?php endif; ?>
                    <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <?php echo $this->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?>
                    <?php else: ?>
                        <?php echo $this->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br />
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount'], true, true); ?></span><br />
                                <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'], true, true); ?></small></span><br />
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span><br />
                                <?php endforeach; ?>
                            </small>
                        <?php endif; ?>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php } ?>
		</tbody>
	</table>
</div>


<script>

    function remove_item(item_id){
        jQuery('#order_item_'+item_id).hide();
        jQuery('#item_qty_'+item_id).val(0);
        order.itemsUpdate();
    }

</script>