<?php
$currAdminId    = Mage::getSingleton('admin/session')->getUser()->getId();
$quote          = Mage::getSingleton('adminhtml/session_quote')->getQuote();
$couponCode     = $quote->getCouponCode();
$coupon         = Mage::getModel('salesrule/coupon')->load($couponCode, 'code');
$couponRule     = Mage::getModel('salesrule/rule')->load($coupon->getRuleId());
?>

<div class="subtotal">
    <table width="100%" cellspacing="0">
        <colgroup>
            <col>
            <col width="1">
        </colgroup>
        <tbody>
        <tr>
            <td class="label a-right">
                <strong>Order Discount</strong>
            </td>
            <td class="emph a-right">
                <input name="" class="input-text input-discount" value="<?php echo sprintf('%0.2f', $couponRule->getDiscountAmount()); ?>">
            </td>
        </tr>
        <tr>
            <td class="label a-right">
                <strong>Subtotal</strong>
            </td>
            <td class="emph a-right">
                <strong class="txt-subtotal"><?php echo $this->formatPrice($this->getTotalData('subtotal')); ?></strong>
            </td>
        </tr>
        <tr>
            <td class="label a-right">
                <strong >Tax</strong>
            </td>
            <td class="emph a-right">
                <strong class="txt-tax"><?php echo $this->formatPrice($this->getTotalData('tax')); ?></strong>
            </td>
        </tr>
        <tr>
            <td class="label a-right">
                <strong>Grand Total</strong>
            </td>
            <td class="emph a-right">
                <strong class="txt-grand-total"><?php echo $this->formatPrice($this->getTotalData('grand_total')); ?></strong>
            </td>
        </tr>
        <tr>
            <td class="label a-right">
                <strong>Total Paid</strong>
            </td>
            <td class="emph a-right">
                <strong class="txt-total-paid"><?php echo $this->formatPrice($this->getTotalData('grand_total')); ?></strong>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<script>
    (function($,W,D){
        $(D).ready(function() {
            var decimalOnly = function(str) {
                str = str.replace(new RegExp(',', 'g'), '');
                return parseFloat(str.match(/[\d\.]+/));
            };

            $('.input-discount').blur(function() {
                var $this       = $(this),
                    quoteId     = $("#quote_id").val(),
                    quotationId = $("#quotation_id").val(),
                    discount    = $this.val();

                $('#loading-mask').show();

                if((discount).indexOf('%') !== -1) {
                    var percent = discount.substr(0, discount.length - 1);
                    var subtotal = $('.txt-subtotal .price').text();
                    subtotal = decimalOnly(subtotal);
                    if(percent > 100) {
                        percent = 100;
                        $this.val(100+'%');
                    }
                    if(percent < 0) {
                        percent = 0;
                        $this.val(0+'%');
                    }
                    discount = (subtotal / 100) * percent;
                    discountByPercent = percent;
                }

                $.post('<?php echo $this->
                                getUrl('adminhtml/xb2b/ajaxUpdateTotalDiscountOnAdd') ?>?isAjax=true',
                    {   quote_id: quoteId, quotation_id: quotationId,
                        discount: discount, form_key: FORM_KEY },
                    function(rs) {
                        rs = JSON.parse(rs);
                        var data = rs.data;
                        $('.txt-subtotal .price').text(data.subtotal);
                        $('.txt-grand-total .price').text(data.grand_total);
                        $('.txt-total-paid .price').text(data.grand_total);
                        $('#loading-mask').hide();
                    }
                );
            });
        });
    })(jQuery,window,document);
</script>