<footer class="site-footer" role="contentinfo">
  <div class="page-width">
    <div class="grid grid--rev">
      <div class="grid__item large-up--two-fifths site-footer__section">
        <div class="site-footer__subsection">
          <ul class="list--inline social-icons">
            <li>
              <a href="https://www.facebook.com/AireLibreLatam" title="airelibrelatam en Facebook">
                <svg class="icon icon-facebook" aria-hidden="true" focusable="false">
                  <use xlink:href="#icon-facebook"></use>
                </svg>
                <span class="icon__fallback-text">Facebook</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid__item large-up--three-fifths site-footer__section">
        <div class="grid">
          <div class="grid__item medium-up--one-third site-footer__subsection">
            <h4 class="h1 site-footer__section-title">AireLibreLatam</h4>
            <ul class="site-footer__list">
              <li class="site-footer__list-item"><a href="/pages/nosotros">Nosotros</a></li>
              <li class="site-footer__list-item"><a href="/pages/terminos-y-condiciones">Términos y condiciones</a></li>
              <li class="site-footer__list-item"><a href="/pages/tiendas">Tiendas</a></li>
              <li class="site-footer__list-item"><a href="/pages/contactanos">Contacto</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="site-footer__copyright">
      <div class="page-width">
        <div class="grid medium-up--grid--table">
          <div class="grid__item medium-up--one-half">
            <small>&copy; 2017, <a href="/" title="">airelibrelatam</a>. Asesoría por <a href="http://manamana.com.mx">Manamana Agencia</a></small>
          </div>
          <div class="grid__item medium-up--one-half medium-up--text-right">
            <ul class="list--inline payment-icons">
              <li>
                <svg class="icon icon-american_express" aria-hidden="true" focusable="false">
                  <use xlink:href="#icon-american_express"></use>
                </svg>
                <span class="icon__fallback-text">american express</span>
              </li>
              <li>
                <svg class="icon icon-master" aria-hidden="true" focusable="false">
                  <use xlink:href="#icon-master"></use>
                </svg>
                <span class="icon__fallback-text">master</span>
              </li>
              <li>
                <svg class="icon icon-paypal" aria-hidden="true" focusable="false">
                  <use xlink:href="#icon-paypal"></use>
                </svg>
                <span class="icon__fallback-text">paypal</span>
              </li>
              <li>
                <svg class="icon icon-visa" aria-hidden="true" focusable="false">
                  <use xlink:href="#icon-visa"></use>
                </svg>
                <span class="icon__fallback-text">visa</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</footer>