<?php

$customer = $this->getCurrentCustomer();
$supporters = $this->getSupporters();
$time_refresh = Mage::getStoreConfig('xb2b/general/chat_speed');
if(empty($time_refresh)) $time_refresh = 3000;

?>

<script>
    var TIME_REFRESH     = <?php echo $time_refresh; ?>;
    var CUSTOMER_ID      = '<?php echo $customer->getId(); ?>';
    var CUSTOMER_NAME    = '<?php echo $this->getCustomerName(); ?>';
</script>

<div id="xb2b_status_bar">
    <span class="default-text">Chat with supporter &uarr;</span>
    <span class="notification-text"> <strong>0</strong> new messages &uarr;</span>
</div>
<div id="xb2b_main_box">
    <input type="text" placeholder="supporter filter..." class="partner-filter" />
    <div class="current-user"><span class="focus-name"></span></div>
    <a class="btn-close-chatbox btn-link"><span class="emdash"></span></a>

    <div class="boxes clearfix">
        <ul class="supporter-list">
            <?php foreach($supporters as $sid => $supporter):?>
                <li class="supporter" data-id="<?php echo $sid; ?>">
                    <span class="status"></span>
                    <span class="sname"><?php echo $supporter->getFirstname() . ' ' . $supporter->getLastname(); ?></span>
                    <span class="unread"></span>
                </li>
            <?php endforeach; ?>
        </ul>

        <div class="screen">
            <?php foreach($supporters as $sid => $supporter): ?>
                <div class="date-navigator" data-id="<?php echo $supporter->getId(); ?>">
                    Show messages from <a class="select-date"></a>
                </div>
                <ul class="msg-list msg-list-<?php echo $sid; ?>"></ul>
            <?php endforeach; ?>
            <div class="enter clearfix">
                <textarea class="txt-in-msg" id="input_message"></textarea>
                <button class="btn-send">Send</button>
            </div>
        </div>
    </div>
</div>